web:
  image:
    repository: 159207264407.dkr.ecr.us-east-2.amazonaws.com/cap-web
    tag: sha-0f52660e81dd4947ca330319f99d247a74a25c8f
    pullPolicy: IfNotPresent
  publicUrl: https://cap.take3tech.dev
  nextauthUrl: https://cap.take3tech.dev
  allowedSignupDomains: take3tech.com
mediaServer:
  image:
    repository: 159207264407.dkr.ecr.us-east-2.amazonaws.com/cap-media-server
    tag: sha-0f52660e81dd4947ca330319f99d247a74a25c8f
    pullPolicy: IfNotPresent
serviceAccount:
  name: cap-web
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::159207264407:role/IRSA-takethree-cap-web
storage:
  bucket: takethree-cap-production-159207264407-us-east-2
  region: us-east-2
  publicEndpoint: ""
  internalEndpoint: ""
  pathStyle: "false"
  bootstrap: "false"
email:
  provider: smtp
  from: Cap <no-reply@take3tech.com>
  smtp:
    host: smtp.postmarkapp.com
    port: "587"
    secure: "false"
    requireTls: "true"
minio:
  enabled: false
ingress:
  webHost: cap.take3tech.dev
